def install_skill(skill_dir):
  # ... existing code ...
  # Add support for Agent Plugins layout
  if os.path.exists(os.path.join(skill_dir, 'plugin.json')):
    with open(os.path.join(skill_dir, 'plugin.json')) as f:
      plugin_manifest = json.load(f)
    # ... process plugin manifest ...
  # ... existing code ...
